-- إدراج الشركات الأردنية مع تجنب التكرار (حسب البريد الإلكتروني)
INSERT INTO Users (FullName, Email, Password, Role, IsAdmin, CompanyName)
SELECT * FROM (
    VALUES 
        ('Zain Jordan', 'zain@example.com', '123456', 'Company', 0, 'Zain Jordan'),
        ('Orange Jordan', 'orange@example.com', '123456', 'Company', 0, 'Orange Jordan'),
        ('Umniah', 'umniah@example.com', '123456', 'Company', 0, 'Umniah'),
        ('Arab Bank', 'arabbank@example.com', '123456', 'Company', 0, 'Arab Bank'),
        ('Bank al Etihad', 'bankaletihad@example.com', '123456', 'Company', 0, 'Bank al Etihad'),
        ('Cairo Amman Bank', 'cairoamman@example.com', '123456', 'Company', 0, 'Cairo Amman Bank'),
        ('Jordan Ahli Bank', 'ahlibank@example.com', '123456', 'Company', 0, 'Jordan Ahli Bank'),
        ('Hikma Pharmaceuticals', 'hikma@example.com', '123456', 'Company', 0, 'Hikma Pharmaceuticals'),
        ('Nuqul Group', 'nuqul@example.com', '123456', 'Company', 0, 'Nuqul Group'),
        ('Arab Potash', 'arabpotash@example.com', '123456', 'Company', 0, 'Arab Potash'),
        ('Jordan Phosphate Mines', 'jpmc@example.com', '123456', 'Company', 0, 'Jordan Phosphate Mines'),
        ('Maktoob Group', 'maktoob@example.com', '123456', 'Company', 0, 'Maktoob Group'),
        ('Extensya', 'extensya@example.com', '123456', 'Company', 0, 'Extensya'),
        ('ProgressSoft', 'progressoft@example.com', '123456', 'Company', 0, 'ProgressSoft'),
        ('OpenSooq', 'opensooq@example.com', '123456', 'Company', 0, 'OpenSooq'),
        ('MarkaVIP', 'markavip@example.com', '123456', 'Company', 0, 'MarkaVIP'),
        ('Abdali Mall', 'abdali@example.com', '123456', 'Company', 0, 'Abdali Mall'),
        ('Taj Mall', 'tajmall@example.com', '123456', 'Company', 0, 'Taj Mall'),
        ('City Mall', 'citymall@example.com', '123456', 'Company', 0, 'City Mall'),
        ('Hyatt Amman', 'hyatt@example.com', '123456', 'Company', 0, 'Hyatt Amman'),
        ('Four Seasons Amman', 'fourseasons@example.com', '123456', 'Company', 0, 'Four Seasons Amman'),
        ('St Regis Amman', 'stregis@example.com', '123456', 'Company', 0, 'St Regis Amman'),
        ('Royal Jordanian Airlines', 'rj@example.com', '123456', 'Company', 0, 'Royal Jordanian Airlines'),
        ('Air Arabia Jordan', 'airarabia@example.com', '123456', 'Company', 0, 'Air Arabia Jordan'),
        ('Caterpillar Jordan', 'caterpillar@example.com', '123456', 'Company', 0, 'Caterpillar Jordan'),
        ('Mercedes-Benz Jordan', 'mercedes@example.com', '123456', 'Company', 0, 'Mercedes-Benz Jordan'),
        ('Toyota Jordan', 'toyota@example.com', '123456', 'Company', 0, 'Toyota Jordan'),
        ('Hyundai Jordan', 'hyundai@example.com', '123456', 'Company', 0, 'Hyundai Jordan'),
        ('Kia Jordan', 'kia@example.com', '123456', 'Company', 0, 'Kia Jordan'),
        ('Nissan Jordan', 'nissan@example.com', '123456', 'Company', 0, 'Nissan Jordan'),
        ('Ford Jordan', 'ford@example.com', '123456', 'Company', 0, 'Ford Jordan'),
        ('BMW Jordan', 'bmw@example.com', '123456', 'Company', 0, 'BMW Jordan'),
        ('Audi Jordan', 'audi@example.com', '123456', 'Company', 0, 'Audi Jordan'),
        ('Volkswagen Jordan', 'vw@example.com', '123456', 'Company', 0, 'Volkswagen Jordan'),
        ('Pepsi Jordan', 'pepsi@example.com', '123456', 'Company', 0, 'Pepsi Jordan'),
        ('Coca-Cola Jordan', 'cocacola@example.com', '123456', 'Company', 0, 'Coca-Cola Jordan'),
        ('Nestle Jordan', 'nestle@example.com', '123456', 'Company', 0, 'Nestle Jordan'),
        ('Unilever Jordan', 'unilever@example.com', '123456', 'Company', 0, 'Unilever Jordan'),
        ('Procter & Gamble Jordan', 'pg@example.com', '123456', 'Company', 0, 'Procter & Gamble Jordan'),
        ('Samsung Jordan', 'samsung@example.com', '123456', 'Company', 0, 'Samsung Jordan'),
        ('LG Jordan', 'lg@example.com', '123456', 'Company', 0, 'LG Jordan'),
        ('Apple Jordan', 'apple@example.com', '123456', 'Company', 0, 'Apple Jordan'),
        ('Microsoft Jordan', 'microsoft@example.com', '123456', 'Company', 0, 'Microsoft Jordan'),
        ('Oracle Jordan', 'oracle@example.com', '123456', 'Company', 0, 'Oracle Jordan'),
        ('IBM Jordan', 'ibm@example.com', '123456', 'Company', 0, 'IBM Jordan'),
        ('Cisco Jordan', 'cisco@example.com', '123456', 'Company', 0, 'Cisco Jordan'),
        ('Deloitte Jordan', 'deloitte@example.com', '123456', 'Company', 0, 'Deloitte Jordan'),
        ('PwC Jordan', 'pwc@example.com', '123456', 'Company', 0, 'PwC Jordan'),
        ('EY Jordan', 'ey@example.com', '123456', 'Company', 0, 'EY Jordan'),
        ('KPMG Jordan', 'kpmg@example.com', '123456', 'Company', 0, 'KPMG Jordan'),
        ('Abu Khader Group', 'abukhader@example.com', '123456', 'Company', 0, 'Abu Khader Group'),
        ('Kawar Group', 'kawar@example.com', '123456', 'Company', 0, 'Kawar Group'),
        ('Zara Investment', 'zara@example.com', '123456', 'Company', 0, 'Zara Investment'),
        ('Jordan Telecom Group', 'jtg@example.com', '123456', 'Company', 0, 'Jordan Telecom Group'),
        ('FastLink', 'fastlink@example.com', '123456', 'Company', 0, 'FastLink'),
        ('Eco Energy', 'ecoenergy@example.com', '123456', 'Company', 0, 'Eco Energy'),
        ('Philadelphia Solar', 'philadelphiasolar@example.com', '123456', 'Company', 0, 'Philadelphia Solar'),
        ('Al-Taj Engineering', 'altaj@example.com', '123456', 'Company', 0, 'Al-Taj Engineering'),
        ('Modern Electronics', 'modernelec@example.com', '123456', 'Company', 0, 'Modern Electronics'),
        ('Jordan Aviation', 'aviation@example.com', '123456', 'Company', 0, 'Jordan Aviation')
) AS newCompany (FullName, Email, Password, Role, IsAdmin, CompanyName)
WHERE NOT EXISTS (SELECT 1 FROM Users WHERE Email = newCompany.Email);